# Data types in Numpy

In [ ]:
i - integer
b-boolean
u -unsigned integer
f-float
c-complex float
M- datetime
O- object
S-strings

# Examples

In [1]:
import numpy as np

In [2]:
#integer
num = np.array([20,30,40,50,60])
print(num)
print(num.dtype)

[20 30 40 50 60]
int32


In [7]:
#convert data type from integer to boolean
xyz = np.array([200,0,380,000,300,989])
newarray = xyz.astype(bool)
print(newarray)
print(newarray.dtype)

[ True False  True False  True  True]
bool


In [4]:
x = np.array([1,22,38,91,39,0])
y = x.astype(bool)
print(y)
print(y.dtype)

[ True  True  True  True  True False]
bool


In [11]:
#float
xyz = np.array([1.2,3.9,2.88,1.9,5.0])
print(xyz)
print(xyz.dtype)

[1.2  3.9  2.88 1.9  5.  ]
float64


In [19]:
#copy method
electrics = np.array(["fan","tv","Ac","washing machine","car"," music box"])
tools = electrics.copy()
print(tools)
electrics[-2] = "bike"
print(electrics)

['fan' 'tv' 'Ac' 'washing machine' 'car' ' music box']
['fan' 'tv' 'Ac' 'washing machine' 'bike' ' music box']


In [22]:
#view method
languages = np.array(["python","c++","c","java","meshine","HTML"])
imp = languages.view()
languages[2] = "full stack"
print(imp)
print(languages)

['python' 'c++' 'full st' 'java' 'meshine' 'HTML']
['python' 'c++' 'full st' 'java' 'meshine' 'HTML']


In [24]:
# convert float to integer by using [i] parameter
xyz = np.array([1.0,3.4,5.3,2.9])
newarray = xyz.astype('i')
print(newarray)
print(newarray.dtype)

[1 3 5 2]
int32


# Reshaping Arrays

-Changing the shape of an array.


In [29]:
#coverting the 1-D array into 2-D array with 20 elements.

In [28]:
even_num = np.array([2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40])
print(even_num.size)
newarr = even_num.reshape(5,4)
print(newarr)

20
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]]


In [30]:
#converting the 1_D array to 3-D array with 20 elements

In [38]:
odd_num =np.array([1,3,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41])
print(odd_num.size)
newarr = odd_num.reshape(2,5,2)
print(newarr)

20
[[[ 1  3]
  [ 7  9]
  [11 13]
  [15 17]
  [19 21]]

 [[23 25]
  [27 29]
  [31 33]
  [35 37]
  [39 41]]]


# By using Arthimatic operations

In [41]:
x = np.array([[15,18,39],
             [21,30,2],
             [22,33,11]],dtype=np.float32)
y = np.array([[22,33,11],
             [9,8,2],
             [16,19,10]],dtype = np.float32)
print(x+y)

[[37. 51. 50.]
 [30. 38.  4.]
 [38. 52. 21.]]


In [44]:
print(x-y)
print(x*y)
print(x/y)
print(x%y)

[[ -7. -15.  28.]
 [ 12.  22.   0.]
 [  6.  14.   1.]]
[[330. 594. 429.]
 [189. 240.   4.]
 [352. 627. 110.]]
[[0.6818182  0.54545456 3.5454545 ]
 [2.3333333  3.75       1.        ]
 [1.375      1.7368422  1.1       ]]
[[15. 18.  6.]
 [ 3.  6.  0.]
 [ 6. 14.  1.]]


In [46]:
A = np.array([[[1,8,3,16],[2,4,18,10]],
              [[3,9,18,11],[13,16,18,1]],
              [[22,21,41,10],[10,19,2,6]]])
B = np.array([[[2,8,1,9],[2,7,9,11]],
              [[19,18,17,2],[17,29,11,10]],
              [[1,2,3,4],[5,6,7,8]]])
print(A+B)

[[[ 3 16  4 25]
  [ 4 11 27 21]]

 [[22 27 35 13]
  [30 45 29 11]]

 [[23 23 44 14]
  [15 25  9 14]]]


In [47]:
print(A-B)

[[[ -1   0   2   7]
  [  0  -3   9  -1]]

 [[-16  -9   1   9]
  [ -4 -13   7  -9]]

 [[ 21  19  38   6]
  [  5  13  -5  -2]]]


In [49]:
print(A/B)

[[[ 0.5         1.          3.          1.77777778]
  [ 1.          0.57142857  2.          0.90909091]]

 [[ 0.15789474  0.5         1.05882353  5.5       ]
  [ 0.76470588  0.55172414  1.63636364  0.1       ]]

 [[22.         10.5        13.66666667  2.5       ]
  [ 2.          3.16666667  0.28571429  0.75      ]]]


In [51]:
print(np.sqrt(A))
print(np.sqrt(B))

[[[1.         2.82842712 1.73205081 4.        ]
  [1.41421356 2.         4.24264069 3.16227766]]

 [[1.73205081 3.         4.24264069 3.31662479]
  [3.60555128 4.         4.24264069 1.        ]]

 [[4.69041576 4.58257569 6.40312424 3.16227766]
  [3.16227766 4.35889894 1.41421356 2.44948974]]]
[[[1.41421356 2.82842712 1.         3.        ]
  [1.41421356 2.64575131 3.         3.31662479]]

 [[4.35889894 4.24264069 4.12310563 1.41421356]
  [4.12310563 5.38516481 3.31662479 3.16227766]]

 [[1.         1.41421356 1.73205081 2.        ]
  [2.23606798 2.44948974 2.64575131 2.82842712]]]


# Sorting Array

sorting array means putting the elements in an ordered sequence.

In [54]:
xyz  = np.array(["electric","power","Motor","CURRENT","AMPLe"])
print(np.sort(xyz))

['AMPLe' 'CURRENT' 'Motor' 'electric' 'power']


# Slicing Array

In [57]:
college = np.array(["vaagdevi","jayamuki","bits","ku","omg","newscience","Acharya","geethanjali","kits"])
print(college[2:7])
print(college[-5])
print(college[ : ])

['bits' 'ku' 'omg' 'newscience' 'Acharya']
omg
['vaagdevi' 'jayamuki' 'bits' 'ku' 'omg' 'newscience' 'Acharya'
 'geethanjali' 'kits']


In [60]:
print(np.sort(college))

['Acharya' 'bits' 'geethanjali' 'jayamuki' 'kits' 'ku' 'newscience' 'omg'
 'vaagdevi']


In [61]:
print(np.copy(college))

['vaagdevi' 'jayamuki' 'bits' 'ku' 'omg' 'newscience' 'Acharya'
 'geethanjali' 'kits']
