# Numpy

In [2]:
!pip install numpy

In [3]:
import numpy as np

# create numpy

In [13]:
# creating numpy
a = np.array([1,4,5,99,29])
b = np.array([[39,10,29,30],[2,3,88,12]])


In [14]:
print(a)
print(b)

[ 1  4  5 99 29]
[[39 10 29 30]
 [ 2  3 88 12]]


# Initial place holders

In [78]:
import numpy as np

In [29]:
#create an array with zero's
np.zeros([5,4])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
#create an array with one's
np.ones([4,2,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# create an array of evenly space values

In [43]:
d = np.arange(100,150,6)
print(d)

[100 106 112 118 124 130 136 142 148]


In [45]:
x = np.arange(10.2,15.2,0.2)
print(x)

[10.2 10.4 10.6 10.8 11.  11.2 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8
 13.  13.2 13.4 13.6 13.8 14.  14.2 14.4 14.6 14.8 15. ]


# create an array of evenly spaced values(sample values)

In [48]:
np.linspace(10,20,15)


array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

# create an constant array

In [60]:
#create an 3D array
xyz = np.full((2,4,3), 95)
print(xyz)

[[[95 95 95]
  [95 95 95]
  [95 95 95]
  [95 95 95]]

 [[95 95 95]
  [95 95 95]
  [95 95 95]
  [95 95 95]]]


In [62]:
#create an 2Darray
n=22
xyz = np.full((5,3),n-2)
print(xyz)

[[20 20 20]
 [20 20 20]
 [20 20 20]
 [20 20 20]
 [20 20 20]]


In [61]:
#create an 1D array
xyz = np.full((7),9*2)
print(xyz)

[18 18 18 18 18 18 18]


# create an identify matrix 

In [64]:
x = np.eye(2*2)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [71]:
# create an array with randam values
np.random.random((3,6))

array([[0.80428052, 0.94655455, 0.11297335, 0.29984544, 0.68326462,
        0.64845257],
       [0.08503953, 0.11007941, 0.29582582, 0.63325008, 0.26893816,
        0.14309402],
       [0.90151604, 0.14529815, 0.92925125, 0.70279089, 0.81204686,
        0.45114747]])

In [75]:
#To find shape of array
xyz = np.array([[2,3,4,5],
               [4,5,7,9],
               [2,3,4,5]])
print(xyz.shape)

(3, 4)


In [77]:
#To find len array
x = np.array([[2,3,2,3],
              [2,5,6,4],
              [9,2,5,8],
              [2,8,1,3],
              [8,9,2,1],
              [9,1,3,8]])
len(x)

6

# Accessing Element from the array.

In [79]:
numb = np.array([1,3,77,28,39,10,33,11,39,108])
print(numb[6])
print(numb[3])
print(numb[-2])
print(numb[-6])
print(numb[0])

33
28
39
39
1


In [84]:
name = np.array(['Akhil','manish','shirisha','Sunny','bunny'])
print(name[3])
print(name[-5])
print(name[ :3])

Sunny
Akhil
['Akhil' 'manish' 'shirisha']


In [87]:
#addition two index position

xyz = np.array([2,11,18,29,3,5,8,12,21,10])
print(xyz[3]+xyz[4]+xyz[0]+xyz[-3])
print(xyz[2]*xyz[5])
print(xyz[6]-xyz[-3])

46
90
-4


# Access the 2D array.

In [89]:
num = np.array([[9,2,12,27,28,19],
                [3,4,5,6,9,98],
                [9,8,71,12,3,1],
                [29,39,12,32,12,23]])
print("5th element on 3 row :",num[3,5])

5th element on 3 row : 23


In [90]:
print("-2nd element on 0 row :",num[0,-2])

-2nd element on 0 row : 28


In [2]:
import numpy as np

# Access the 3D array.

In [8]:
y = np.array([[[3,4,7,7,2], [3,8,23,11,9]],
               [[2,8,9,12,21], [22,11,33,44,55]],
               [[3,34,21,3,1], [33,23,43,53,63]],
               [[22,88,91,21,4], [21,32,41,51,61]],
               [[32,44,55,34,99], [90,80,70,60,50]]])
print(y[2,1,3])
print(y[0,0,-1])

53
2
